
#### ----- OPTIMIZER HYPERPARAMETERS ----- ####
evotorch:
  algorithm: 'SNES'

dfo_args_general:
  max_generations: 150

snes:
  center_init: 0
  radius_init: 5
  center_learning_rate: 0.2
  popsize: 50000
  stdev_max_change: 0.05





neural_network:
  attention_linear_in_features: 3
  attention_linear_out_features: 3
  qkv_out_features: 9
  ffn_input: 12
  ffn_hidden: 3
  linear1_in_features: 3
  linear1_out_features: 3
  linear_in_features: 12
  heuristic_rules_1: 5
  heuristic_rules_2: 7
  heuristic_rules_3: 5 

policy:
  name: "AttentionPolicy"
  samples: 1
  state_size: 5
  price_state_size: 3
  state:
    electricity_price: # calculated from list of prices
      mean: 67.67
      std: 23.51
    sp_price: # calculated from list of prices
      mean: 6.29
      std: 2.37
    generation: # calculated from list of generation
      mean: 11.80
      std: 9.29
    state_space: 
      mean_f_id: 11.50
      std_f_id: 3.83

      mean_f_pt: 47
      std_f_pt: 15.67

      mean_f_st: 47
      std_f_st: 15.67

      mean_f_et: 47.5
      std_f_et: 15.83

      mean_f_pe: 0.5
      std_f_pe: 0.5


EAF:
  SPT:
    ranking_1: [1, 2, 3, 4, 17, 18, 19, 20,21, 22, 23, 24]
    ranking_2: [5, 6, 7, 8, 13, 14, 15, 16]
    ranking_3: [9, 10, 11, 12]

  LPT:
    ranking_1: [9, 10, 11, 12]
    ranking_2: [5, 6, 7, 8, 13, 14, 15, 16]
    ranking_3: [1, 2, 3, 4, 17, 18, 19, 20,21, 22, 23, 24]

  SRM:
    ranking_1: [ 7, 8 ]
    ranking_2: [ 1, 2, 3, 4, 13, 14, 15, 16, 17, 21, 22, 23, 24 ]
    ranking_3: [ 5, 6, 20 ]
    ranking_4: [ 9, 10, 11, 12, 18, 19 ]

  LRM:
    ranking_1: [ 9, 10, 11, 12, 18, 19 ]
    ranking_2: [ 5, 6, 20 ]
    ranking_3: [ 1, 2, 3, 4, 13, 14, 15, 16, 17, 21, 22, 23, 24 ]
    ranking_4: [ 7, 8 ]


AOD:
  SPT:
    ranking_1: [1, 2, 3, 4]
    ranking_2: [5, 6, 7, 8, 21, 22, 23, 24]
    ranking_3: [13, 14, 15, 16, 17]
    ranking_4: [9, 10, 11, 12, 18, 19, 20]

  LPT:
    ranking_1: [9, 10, 11, 12, 18, 19, 20]
    ranking_2: [13, 14, 15, 16, 17]
    ranking_3: [5, 6, 7, 8, 21, 22, 23, 24]
    ranking_4: [1, 2, 3, 4]

  SRM:
    ranking_1: [ 7, 8 ]
    ranking_2: [ 13, 14, 15, 16, 17 ]
    ranking_3: [ 20, 21, 22, 23, 24 ]
    ranking_4: [ 1, 2, 3, 4 ]
    ranking_5: [ 5, 6, 9, 10, 11, 12, 18, 19 ]


  LRM:
    ranking_1: [ 5, 6, 9, 10, 11, 12, 18, 19 ]
    ranking_2: [ 1, 2, 3, 4 ]
    ranking_3: [ 20, 21, 22, 23, 24 ]
    ranking_4: [ 13, 14, 15, 16, 17 ]
    ranking_5: [ 7, 8 ]


LF:
  SPT:
    ranking_1: [ 7, 8 ]
    ranking_2: [ 13, 14, 15, 16, 17 ]
    ranking_3: [ 20, 21, 22, 23, 24 ]
    ranking_4: [ 1, 2, 3, 4 ]
    ranking_5: [ 5, 6, 9, 10, 11, 12, 18, 19 ]

  LPT:
    ranking_1: [ 5, 6, 9, 10, 11, 12, 18, 19 ]
    ranking_2: [ 1, 2, 3, 4 ]
    ranking_3: [ 20, 21, 22, 23, 24 ]
    ranking_4: [ 13, 14, 15, 16, 17 ]
    ranking_5: [ 7, 8 ]








################################################## Stages and Equipment data ###########################################


# stage1 : {'id': 1, 'production_equipment': {1: 85, 2: 85}, 'transfer_equipment': {'id': 1}}
stage1 :
  id: 1
  production_equipment:
     1: 85                  # Power rating of EAF1
     2: 85                  # Power rating of EAF2
  transfer_equipment :
     id: 1
  sp_provision:
    MW: 34

# stage2 : {'id': 2, 'production_equipment': {1: 2, 2: 2}, 'transfer_equipment': {'id': 1}}
stage2 :
  id: 2
  production_equipment:
     1: 2                 # Power rating of AOD1
     2: 2                 # Power rating of AOD2
  transfer_equipment:
    id: 1


# stage3 : {'id': 3, 'production_equipment': {1: 2, 2: 2}}
stage3 :
  id: 3
  production_equipment:
     1: 2                 # Power rating of LF1
     2: 2                 # Power rating of LF2


################################################## MIP Data ############################################################

#stage2units : {'1': {'EAF': 2, 'TEAF': 1}, '2': {'AOD': 2, 'TAOD': 1}, '3': {'LF': 2}}
stage2units:                                     # How many units in each stage
  '1':
    EAF: 2
    TEAF: 1
  '2':
    AOD: 2
    TAOD: 1
  '3':
    LF: 2

#MILP_args : {'number_of_heats': 24, 'number_of_stages': 3, 'horizon_periods': 96, 'time_interval': 15,
              #'number_of_hours': 24}
MILP_args:
  number_of_heats: 24                            # No of products
  number_of_stages: 3                            # No of stages
  horizon_periods: 96                            # NO of discrete periods
  time_interval: 15                              # Duration in minutes of one period
  number_of_hours: 24                            # Number of hours
  number_of_production_units: 6                  # Total number of production units
  number_of_transfer_units: 2                    # Total number of transfer units
  log_interval: 10                               # store information after every 10 episodes
  hyperparameter: 4                              # for state space matrix to choose most recent 4 tasks





################################################## Heat Data ###########################################################

Heats :

  Heat1:
    id: 1
  Heat2:
    id: 2
  Heat3:
    id: 3
  Heat4:
    id: 4
  Heat5:
    id: 5
  Heat6:
    id: 6
  Heat7:
    id: 7
  Heat8:
    id: 8
  Heat9:
    id: 9
  Heat10:
    id: 10
  Heat11:
    id: 11
  Heat12:
    id: 12
  Heat13:
    id: 13
  Heat14:
    id: 14
  Heat15:
    id: 15
  Heat16:
    id: 16
  Heat17:
    id: 17
  Heat18:
    id: 18
  Heat19:
    id: 19
  Heat20:
    id: 20
  Heat21:
    id: 21
  Heat22:
    id: 22
  Heat23:
    id: 23
  Heat24:
    id: 24

Equipment:
  EAF:
    processing_time:
      Heat1: 80.0
      Heat2: 80.0
      Heat3: 80.0
      Heat4: 80.0
      Heat5: 85.0
      Heat6: 85.0
      Heat7: 85.0
      Heat8: 85.0
      Heat9: 90.0
      Heat10: 90.0
      Heat11: 90.0
      Heat12: 90.0
      Heat13: 85.0
      Heat14: 85.0
      Heat15: 85.0
      Heat16: 85.0
      Heat17: 80.0
      Heat18: 80.0
      Heat19: 80.0
      Heat20: 80.0
      Heat21: 80.0
      Heat22: 80.0
      Heat23: 80.0
      Heat24: 80.0
    duration:
      Heat1: 6
      Heat2: 6
      Heat3: 6
      Heat4: 6
      Heat5: 6
      Heat6: 6
      Heat7: 6
      Heat8: 6
      Heat9: 6
      Heat10: 6
      Heat11: 6
      Heat12: 6
      Heat13: 6
      Heat14: 6
      Heat15: 6
      Heat16: 6
      Heat17: 6
      Heat18: 6
      Heat19: 6
      Heat20: 6
      Heat21: 6
      Heat22: 6
      Heat23: 6
      Heat24: 6
  AOD:
    processing_time:
      Heat1: 75.0
      Heat2: 75.0
      Heat3: 75.0
      Heat4: 75.0
      Heat5: 80.0
      Heat6: 80.0
      Heat7: 80.0
      Heat8: 80.0
      Heat9: 95.0
      Heat10: 95.0
      Heat11: 95.0
      Heat12: 95.0
      Heat13: 85.0
      Heat14: 85.0
      Heat15: 85.0
      Heat16: 85.0
      Heat17: 85.0
      Heat18: 95.0
      Heat19: 95.0
      Heat20: 95.0
      Heat21: 80.0
      Heat22: 80.0
      Heat23: 80.0
      Heat24: 80.0
    duration:
      Heat1: 5
      Heat2: 5
      Heat3: 5
      Heat4: 5
      Heat5: 6
      Heat6: 6
      Heat7: 6
      Heat8: 6
      Heat9: 7
      Heat10: 7
      Heat11: 7
      Heat12: 7
      Heat13: 6
      Heat14: 6
      Heat15: 6
      Heat16: 6
      Heat17: 6
      Heat18: 7
      Heat19: 7
      Heat20: 7
      Heat21: 6
      Heat22: 6
      Heat23: 6
      Heat24: 6
  LF:
    processing_time:
      Heat1: 35.0
      Heat2: 35.0
      Heat3: 35.0
      Heat4: 35.0
      Heat5: 45.0
      Heat6: 45.0
      Heat7: 20.0
      Heat8: 20.0
      Heat9: 45.0
      Heat10: 45.0
      Heat11: 45.0
      Heat12: 45.0
      Heat13: 25.0
      Heat14: 25.0
      Heat15: 25.0
      Heat16: 25.0
      Heat17: 25.0
      Heat18: 45.0
      Heat19: 45.0
      Heat20: 30.0
      Heat21: 30.0
      Heat22: 30.0
      Heat23: 30.0
      Heat24: 30.0
    duration:
      Heat1: 3
      Heat2: 3
      Heat3: 3
      Heat4: 3
      Heat5: 3
      Heat6: 3
      Heat7: 2
      Heat8: 2
      Heat9: 3
      Heat10: 3
      Heat11: 3
      Heat12: 3
      Heat13: 2
      Heat14: 2
      Heat15: 2
      Heat16: 2
      Heat17: 2
      Heat18: 3
      Heat19: 3
      Heat20: 2
      Heat21: 2
      Heat22: 2
      Heat23: 2
      Heat24: 2



TEquipment:
  TEAF:
    min_transfer_time:
      Heat1: 1
      Heat2: 1
      Heat3: 1
      Heat4: 1
      Heat5: 1
      Heat6: 1
      Heat7: 1
      Heat8: 1
      Heat9: 1
      Heat10: 1
      Heat11: 1
      Heat12: 1
      Heat13: 1
      Heat14: 1
      Heat15: 1
      Heat16: 1
      Heat17: 1
      Heat18: 1
      Heat19: 1
      Heat20: 1
      Heat21: 1
      Heat22: 1
      Heat23: 1
      Heat24: 1
    max_transfer_time:
      Heat1: 16
      Heat2: 16
      Heat3: 16
      Heat4: 16
      Heat5: 16
      Heat6: 16
      Heat7: 16
      Heat8: 16
      Heat9: 16
      Heat10: 16
      Heat11: 16
      Heat12: 16
      Heat13: 16
      Heat14: 16
      Heat15: 16
      Heat16: 16
      Heat17: 16
      Heat18: 16
      Heat19: 16
      Heat20: 16
      Heat21: 16
      Heat22: 16
      Heat23: 16
      Heat24: 16
  TAOD:
    min_transfer_time:
      Heat1: 1
      Heat2: 1
      Heat3: 1
      Heat4: 1
      Heat5: 1
      Heat6: 1
      Heat7: 1
      Heat8: 1
      Heat9: 1
      Heat10: 1
      Heat11: 1
      Heat12: 1
      Heat13: 1
      Heat14: 1
      Heat15: 1
      Heat16: 1
      Heat17: 1
      Heat18: 1
      Heat19: 1
      Heat20: 1
      Heat21: 1
      Heat22: 1
      Heat23: 1
      Heat24: 1
    max_transfer_time:
      Heat1: 16
      Heat2: 16
      Heat3: 16
      Heat4: 16
      Heat5: 16
      Heat6: 16
      Heat7: 16
      Heat8: 16
      Heat9: 16
      Heat10: 16
      Heat11: 16
      Heat12: 16
      Heat13: 16
      Heat14: 16
      Heat15: 16
      Heat16: 16
      Heat17: 16
      Heat18: 16
      Heat19: 16
      Heat20: 16
      Heat21: 16
      Heat22: 16
      Heat23: 16
      Heat24: 16


  #################################################################







